backend:
  name: git-gateway
  branch: hugo
publish_mode: editorial_workflow
#site_url: https://www.thomasazar.net
#logo_url: https://www.thomasazar.net/uploads/logo.svg
media_folder: "content/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    label_singular: "Newsletter"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: "date"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Adobe newsletter link", name: "iframe", widget: "string"}
  - name: "divisions"
    label: "Divisions"
    label_singular: "Division"
    folder: "content/divisions"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}